### ISSUE TITLE
Error response in civicrm_api3() don't have 'is_error' and 'error_code' filed.

### ISSUE THREAD

**Issue by awg-github** [mecachisenros/civicrm-wp-rest#5]
Joomla and Drupal returns standard error response. 
But when use this plugin  - response is changed(don't have `is_error` and `error_code` filed)

CiviCRM error response with plugin:
![Selection_008](https://user-images.githubusercontent.com/36959503/63606290-633c1300-c5d8-11e9-82b2-e047ed96e807.png)

Standard CiviCRM error response:
![Selection_009](https://user-images.githubusercontent.com/36959503/63606514-ebbab380-c5d8-11e9-8aea-e1cc7aad253e.png)

Could you add `is_error` and `error_code` filed?

**Comment by mecachisenros** [comment]
@awg-github can you test this two commits 3507646eed52119f9e5ea1165472880383854d58, 77155949c602b3ac671893f07a4a3fb27b780cff they should standardise the error responses for the `rest` endpoint.

**Comment by awg-github** [comment]
@mecachisenros , thanks for fast  answer!

Looks good. API returns the same error response.
